# Generated by Django 5.1.2 on 2025-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fruit_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
