# Generated by Django 5.1.2 on 2025-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imag', models.ImageField(upload_to='media/fruit_images')),
                ('body', models.TextField()),
                ('edible', models.BooleanField(default=True)),
            ],
        ),
    ]
