# Generated by Django 5.1.2 on 2025-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='imag',
            field=models.ImageField(upload_to='fruit_images/'),
        ),
    ]
